---
- name: Install PHP
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Restart apache after PHP install
  service:
    name: apache2
    state: restarted
